### ISSUE TITLE
Index file argument broken

### ISSUE THREAD

**Issue by shirounanashi** [RVC-Project/Retrieval-based-Voice-Conversion#25]
When I set the index rate to 0.75 or 0.7 (I haven't tried with other values) this message appears. 

```
Traceback (most recent call last):
  File "D:\Biblioteca\Documentos\RVC Project\Retrieval-based-Voice-Conversion-develop\rvc\modules\vc\pipeline.py", line 307, in pipeline
    index = faiss.read_index(file_index)
  File "C:\Users\Guilherme\AppData\Local\Programs\Python\Python310\lib\site-packages\faiss\swigfaiss_avx2.py", line 10409, in read_index
    return _swigfaiss_avx2.read_index(*args)
TypeError: Wrong number or type of arguments for overloaded function 'read_index'.
  Possible C/C++ prototypes are:
    faiss::read_index(char const *,int)
    faiss::read_index(char const *)
    faiss::read_index(FILE *,int)
    faiss::read_index(FILE *)
    faiss::read_index(faiss::IOReader *,int)
    faiss::read_index(faiss::IOReader *)
```

**Comment by shirounanashi** [comment]
Testing further, I discovered that it has nothing to do with the index rate, but with the keyword argument index file

**Comment by PeterTucker** [comment]
@shirounanashi how did you fix this? I'm getting the same error. Thanks!

**Comment by shirounanashi** [comment]
@PeterTucker Sorry, but as far as I remember, I couldn't fix it

**Comment by PeterTucker** [comment]
@shirounanashi @Tps-F  yeah, looks like it doesn't work for right now.

**Comment by Tps-F** [comment]
I'm sorry I couldn't fix it right now 
I'll check it
